# Generated by Django 3.2.9 on 2021-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211206_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymus_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
